# Generated by Django 5.1.6 on 2025-02-27 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='assembly.assembly')),
                ('products', models.ManyToManyField(related_name='samples', to='products.product')),
            ],
        ),
    ]
