# Generated by Django 4.2.4 on 2025-03-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_at_product_is_active_product_suffix_and_more'),
        ('samples', '0002_remove_sample_release_date_remove_sample_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='products',
            field=models.ManyToManyField(help_text='Produtos associados à amostra.', related_name='samples', to='products.product'),
        ),
    ]
