# Generated by Django 4.2.4 on 2025-03-05 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'ordering': ['name'], 'verbose_name': 'Assembly', 'verbose_name_plural': 'Assemblies'},
        ),
        migrations.AddField(
            model_name='assembly',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01T00:00:00Z', help_text='Data de criação do assembly.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assembly',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização do assembly.'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='name',
            field=models.CharField(help_text='Nome do assembly (deve ser único). Exemplos: KD01 - 1°TURNO, ENGENHARIA/QUALIDADE.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='O nome do assembly deve seguir o formato "KD01 - 1°TURNO" ou "ENGENHARIA/QUALIDADE".', regex='^([A-Z]{2}\\d{2} - \\d°TURNO|ENGENHARIA/QUALIDADE)$')]),
        ),
    ]
