# Generated by Django 5.1.6 on 2025-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='project',
            field=models.CharField(blank=True, choices=[('GM', 'GEM'), ('VW', '27X'), ('23X', '23X'), ('216', '216'), ('ONIX', 'ONIX'), ('MCO', 'MCO'), ('GEM', 'GEM'), ('CRETA', 'CRETA'), ('BR2-HB20', 'BR2-HB20'), ('SU2B-CRETA', 'SU2B-CRETA'), ('Chery', 'Chery 15/T17/T1A')], max_length=100, null=True),
        ),
    ]
