# Generated by Django 4.2.4 on 2025-03-05 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_name_product_part_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o produto está ativo.'),
        ),
        migrations.AddField(
            model_name='product',
            name='suffix',
            field=models.CharField(blank=True, help_text='Sufixo opcional do número da peça (ex.: -BR, -DB).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(help_text='Número da peça no formato IM-XXXXX ou IM-XXXXX-SUFX.', max_length=255, validators=[django.core.validators.RegexValidator(message='O número da peça deve seguir o formato IM-XXXXX ou IM-XXXXX-SUFX.', regex='^IM-\\d{5}(-[A-Z0-9]+)?$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='project',
            field=models.CharField(choices=[('120', '120'), ('120 EU', '120 EU'), ('23X', '23X'), ('27X', '27X'), ('216', '216'), ('ONIX', 'Onix'), ('MCO', 'MCO'), ('GEM', 'GEM'), ('CRETA', 'Creta'), ('BR2-HB20', 'HB20 BR2'), ('SU2B-CRETA', 'Creta SU2B'), ('Chery15/T17/T1A', 'Chery 15/T17/T1A')], default='2025-01-01', help_text='Projeto associado ao produto.', max_length=100),
            preserve_default=False,
        ),
    ]
